export const appConstant = {
  //Routes
  login: 'Login',
  register: 'Register',
  forgot: 'Forgotpassword',
  companydetails: 'Companydetails',
  dashboard: 'Dashboard',
  category: 'Category',
  product: 'Product',
  addproduct: 'Addproduct',
  buyer: 'Buyer',
  orders: 'Orders',
  profile: 'Profile',
  addbuyer: 'Addbuyer',
  viewbuyer: 'Viewbuyer',
  buyerrequest: 'Buyerrequest',
  addOrder: 'Addorder',
  createadd: 'Createaddress',
  vieworder: 'Vieworder',

  //others
  signin: 'Sign in',
  signup: 'Sign up',
  verify: 'Verify your email',
  message:
    'Please verify your email for the verification link. If you have not received the email, we can resend it.',
  name: 'Name',
  setlogo: 'Set logo',
  mobilenumber: 'Mobile Number',
  email: 'Email',
  password: 'Password',
  nameplace: 'Enter your name',
  numberplace: 'Enter your mobile number',
  emailplace: 'Enter your email address',
  passplace: 'Enter your password',
  forgotpassword: 'Forgot password?',
  noaccount: 'Don’t have an account? ',
  haveaccount: 'Already have an account? ',
  token: 'Token',
  sendcode: 'Send Code',
  resend: 'resend',
  ok: 'OK',
  entercompany: 'Enter your company detail',
  resendmessage: 'We sent you email with instructions to reset your password.',
  uploadlogo: 'Upload your logo',
  validemail: 'Please enter valid email address',
  minlength: 'Minimum length should be of 6',
  validname: 'Please enter valid name',
  code: '+91',
  validnumber: 'Please enter valid mobile number',
  validpass: 'Minimum length should be 6',
  error: '!Error',
  danger: 'danger',
  Success: '!Success',
  success: 'success',
  gstno: 'GST No:',
  panno: 'PAN No:',
  gstplace: 'Gst number',
  panplace: 'Pan number',
  complace: 'Company name',
  companyshop: 'Company/Shop Name:',
  compname: 'Name:',
  cname: 'Company Name:',
  phonenumber: 'Phone Number:',
  phoneplace: 'Phone No',
  address: 'Address Name:',
  addplace: 'Address',
  addline: 'Address Line:',
  addlineplace: 'Enter address line',
  locality: 'Locality:',
  localityplace: 'Locality',
  pincode: 'Pincode:',
  pincodeplace: 'Pincode',
  city: 'City:',
  state: 'State:',
  cityplace: 'City',
  stateplace: 'State',
  submit: 'Submit',
  gst: 'GST',
  pan: 'PAN',
  compcode: 'Company Code',
  invalidcomp: 'Invalid company name',
  camera: 'Camera',
  gallery: 'Gallery',
  logoerr: 'Select logo',
  gsterr: 'Invalid gst number',
  panerr: 'Invalid pan number',
  adderr: 'Invalid address',
  addlineerr: 'Invalid address line',
  comperr: 'Invalid company name',
  nameerr: 'Invalid name',
  numerr: 'Invalid number',
  addname: 'Invalid address',
  localerr: 'Invalid locality',
  pinerr: 'Invalid pincode',
  cityerr: 'Invalid city',
  staterr: 'Select state',
  created: 'Your Account is Created Successfully.',
  invitaion: 'Please verify your account in mail with invitation link.',
  selectstate: 'Select State',
  selectcate: 'Select Category',
  searchhere: 'Searh here...',
  greet: 'Hello Good morning',
  catcode: 'Category Code:- ',
  catname: 'Category:- ',
  catecode: 'Category Code: ',
  catename: 'Category Name: ',
  addcate: 'Add Category',
  editcate: 'Edit Category',
  nocatdata: 'No category data found',
  noprodata: 'No product data found',
  nobuyerdata: 'No buyer list found',
  deletemessage: 'Are you sure you want to delete this category?',
  delemessage: 'Are you sure you want to delete this product?',
  cancel: 'Cancel',
  delete: 'Delete',
  importcategory: 'Import Category',
  importproduct: 'Import Product',
  selectsvg: 'Select SVG File',
  downloadcategory: 'Download category sample template',
  downloadproduct: 'Download product sample template',
  proname: 'Name:- ',
  procate: 'Category:- ',
  sku: 'Sku:- ',
  skuplace: 'Sku ',
  unit: 'Unit:- ',
  price: 'Price:- ',
  available: 'Available:- ',
  description: 'Description:- ',
  desc: 'Description ',
  priceplace: 'Price ',
  unitplace: 'Unit ',
  ruppee: '₹',
  lorem:
    'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been',
  addpro: 'Add product',
  editpro: 'Edit product',
  image: 'Image : ',
  productname: 'Name',
  errlogo: 'Select product logo',
  errsku: 'Invalid sku',
  errcate: 'Invalid Category',
  errname: 'Invalid name',
  errprice: 'Invalid price',
  errunit: 'Invalid unit',
  errdescription: 'Invalid description',
  filter: 'Filter',
  reset: 'Reset',
  apply: 'Apply',
  edit: 'Edit',
  dele: 'Delete',

  //BUYER SCREEN
  buyername: 'Buyer Name:-',
  verifybuyer: 'Verify Buyer:-',
  status: 'Status:-',

  //ADDBUYER SCREEN
  addBuyer: 'Add Buyer',
  editBuyer: 'Edit Buyer',
  uplogo: 'Upload logo',
  updatelogo: 'Update logo',
  yes: 'Yes',
  no: 'No',
  active: 'Active',
  inactive: 'Inactive',
  view: 'View',

  //VIEW BUYER
  viewBuyer: 'View Buyer',
  orderdetail: 'Orders Details',
  buyerdetail: 'Buyers Details',
  shopname: 'shop Name:- ',
  Compname: 'company Name:- ',
  Name: 'Name:- ',
  orderno: 'Order Number:- ',
  orderdate: 'Order Date:- ',
  approxdate: 'Approx Deliver Date:- ',
  ddate: 'Deliver Date:- ',
  items: 'Items:- ',
  Totalamount: 'Total Amount:- ',
  partial: 'Partial Delivered',
  delmessage: 'Are you sure you want to delete this buyer?',

  //BUYER REQUEST
  request: 'Buyer Request',
  accept: 'Accept',
  reject: 'Reject',
  norequestdata: 'No buyer request found',
  delerequest: 'Are you sure you want to reject this buyer?',

  //PROFILE
  myprofile: 'My Profile',
  compdetails: 'Company Details',
  changepass: 'Change Password',
  addnewaddress: 'Add New Address',
  addres: 'Address',
  joindate: 'Joined Date',
  logout: 'Logout',
  logoutsuccess: 'Logout Successfully...',
  logoutmessage: 'Are you sure you want to log out from this profile?',
  oldpass: 'Old Password',
  newpass: 'New Password',
  cofirmnewpass: 'Confirm New Password',
  notmatch: 'Confirm password is not matching',
  updateinfo: 'Update Company info',

  //ORDER
  order: 'Order',
  addorder: 'Add Order',
  editorder: 'Edit Order',
  noorderdata: 'No order data found',
  selectdelivery: 'Select Delivery Address',
  selectbilling: 'Select Billing Address',
  one: '1',
  two: '2',
  three: '3',
  bcompany: 'Buyer’s Company: ',
  productName: 'Product Name: ',
  next: 'Next',
  notes: 'Notes',
  Notes: 'Notes: ',
  enternotes: 'Enter notes',
  back: 'Back',
  deliveryadd: 'Delivery Address',
  billingadd: 'Billing Address',
  orderstatus: 'Order Status',
  approxddate: 'Approx Deliver Date ',
  dateplace: 'DD-MM-YYYY',
  statuss: 'Status',
  orderconfirm: 'Order Confirmation',
  buyercompname: 'Buyer Company Name:',
  qty: 'Qty',
  total: 'Total Amount: ',
  shipping: 'Shipping charges: ',
  selectbuyer: 'Select Buyer',
  selectstatus: 'Select Status',
  selectqty: 'Select Quantity',
  quantity: 'Quantity',
  selectproduct: 'Select Product',
  errnote: 'Invalid Notes',
  errapproxdate: 'Select approx date',
  errdeliveryadd: 'Select delivery address',
  errbillingadd: 'Select billing address',
  errstatus: 'Select status',
  zero: '0',
  totalprice: 'Total Price: ',
  pending: 'Pending',
  delivered: 'Delivered',
  partialdelivered: 'Partial Delivered',
  Cancel: 'Cancelled',

  //CREATEADDRESS
  createAdd: 'Create Address',
};
