export const URLS = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  CREATECOMPANY: '/company',
  FORGOTPASSWORD: '/auth/forgot-password',
  RESEND: '/auth/resend-verify-email',
  GETALLCATEGORY: '/categories?',
  ADDCATEGORY: '/categories',
  EDITCATEGORY: '/categories/',
  DELETECATEGORY: '/categories',
  GETALLPRODUCTS: '/product?',
  ADDPRODUCT: '/product',
  DELETEPRODUCT: '/product',
  EDITPRODUCT: '/product/',
  GETALLBUYER: '/companyRelations/getRelations?buyerLists=true',
  CRAETEBUYER: '/company/createbuyer',
  EDITBUYER: '/company/',
  DELETEBUYER: '/company/',
  INACTIVEBUYER: '/companyRelations/acceptRequest/',
};
